FROM maven as build
WORKDIR /app
COPY . .
RUN mvn install
#jdk
FROM openjdk:17-alpine
WORKDIR /app
COPY --from=build /app/target/onlinegrocerystore-0.0.1-SNAPSHOT.jar /app
CMD ["java", "-jar", "onlinegrocerystore-0.0.1-SNAPSHOT.jar"]
